### ISSUE TITLE
[Bug] Unable to login/register using GitHub

### ISSUE THREAD

**Issue by HeroicHitesh** [SenseNet/sensenet#1180]
Unable to login/register with my GitHub account to [SNaaS](https://is.sensenet.com/Account/Login) however, I was able to login/register using my Google account.
I was trying to do this for the **entry challenge**. 
Steps I followed:
- Open [SNaaS](https://is.sensenet.com/Account/Login) in the browser and successfully logged in using my Google account
- Read that we need to use the GitHub account to complete the **entry challenge**, so logged out of the Google account.
- Tried Login/Register using my GitHub account and received the following screen
<img width="1440" alt="500" src="https://user-images.githubusercontent.com/37622734/96417629-2d5fe200-120f-11eb-9340-772e86754da2.png">

**Comment by herflis** [comment]
Hi @HeroicHitesh, there was a bug with the GitHub/Google registration that was fixed in the latest release. Can you please confirm, that you can now login with both your Google and GitHub account? Thanks!

**Comment by HeroicHitesh** [comment]
Hi @herflis, it's still showing the same screen as in original issue description while trying to login using GitHub account

**Comment by herflis** [comment]
Hi @HeroicHitesh, thank you for your quick answer! Can you please check authorized GitHub apps connected to your account? (settings -> applications)  Search for sensenet, please revoke the app (remove from this list) and try to login with your GitHub account to SNaaS again. Thanks! 🙏

![image](https://user-images.githubusercontent.com/6968860/104447865-acf61680-559c-11eb-8d58-ff52543745be.png)
![image](https://user-images.githubusercontent.com/6968860/104447932-c72ff480-559c-11eb-9f82-a1876de4704d.png)

**Comment by HeroicHitesh** [comment]
@herflis Sorry for the late reply was busy with some work. I tried the method you mentioned but it still shows the same screen as mentioned in the issue description.
